#!/bin/bash

out_dir=/usr/share/nginx/html/a/

flags=( --width '900' --full-size-mode --start end-1d --x-grid MINUTE:30:HOUR:1:HOUR:1:0:%l%p --y-grid 5:1 --right-axis 1:0 --slope-mode )
rrd=$HOME/.xdg/data/nest_thermostat.rrd

def=(
  "DEF:temp=${rrd}:temperature:AVERAGE"
  'VDEF:temp_avg=temp,AVERAGE'
  'VDEF:temp_min=temp,MINIMUM'
  'VDEF:temp_max=temp,MAXIMUM'
  'VDEF:temp_cur=temp,LAST'
  'LINE2:temp#FF2200:Hallway Temp\t'
  'GPRINT:temp_cur:\tCur %6.1lf F\t'
  'GPRINT:temp_min:Min %6.1lf F\t'
  'GPRINT:temp_max:Max %6.1lf F\t'
  'GPRINT:temp_avg:Avg %6.1lf F\t'
  'COMMENT:\n'

  "DEF:ext_temperature=${rrd}:ext_temperature:AVERAGE"
  'VDEF:ext_temp_avg=ext_temperature,AVERAGE'
  'VDEF:ext_temp_min=ext_temperature,MINIMUM'
  'VDEF:ext_temp_max=ext_temperature,MAXIMUM'
  'VDEF:ext_temp_cur=ext_temperature,LAST'
  'LINE2:ext_temperature#FF00FF:Exterior Temp\t'
  'GPRINT:ext_temp_cur:\tCur %6.1lf F\t'
  'GPRINT:ext_temp_min:Min %6.1lf F\t'
  'GPRINT:ext_temp_max:Max %6.1lf F\t'
  'GPRINT:ext_temp_avg:Avg %6.1lf F\t'
  'COMMENT:\n'

  "DEF:hum=${rrd}:humidity:AVERAGE"
  'VDEF:hum_avg=hum,AVERAGE'
  'VDEF:hum_min=hum,MINIMUM'
  'VDEF:hum_max=hum,MAXIMUM'
  'VDEF:hum_cur=hum,LAST'
  'LINE1:hum#0000FF:Hallway Humidity\t'
  'GPRINT:hum_cur:Cur %4.0lf%%\t'
  'GPRINT:hum_min:Min %4.0lf%%\t'
  'GPRINT:hum_max:Max %4.0lf%%\t'
  'GPRINT:hum_avg:Avg %4.0lf%%\t'
  'COMMENT:\n'

  "DEF:ext_humidity=${rrd}:ext_humidity:AVERAGE"
  'VDEF:ext_hum_avg=ext_humidity,AVERAGE'
  'VDEF:ext_hum_min=ext_humidity,MINIMUM'
  'VDEF:ext_hum_max=ext_humidity,MAXIMUM'
  'VDEF:ext_hum_cur=ext_humidity,LAST'
  'LINE1:ext_humidity#00FFFF:Exterior Humidity\t'
  'GPRINT:ext_hum_cur:Cur %4.0lf%%\t'
  'GPRINT:ext_hum_min:Min %4.0lf%%\t'
  'GPRINT:ext_hum_max:Max %4.0lf%%\t'
  'GPRINT:ext_hum_avg:Avg %4.0lf%%\t'
  'COMMENT:\n'

  "DEF:target=${rrd}:target:AVERAGE"
  'LINE1:target#555500:Target'
  'COMMENT:\n'

)
rrdtool graph /tmp/nest_a.png --title 'Nest Thermostat' --height '400' "${flags[@]}" -P "${def[@]}" > /dev/null

def=(
  "DEF:power=${rrd}:solar_power:AVERAGE"
  'LINE1:power#0000FF:Solar Power Production\n'
)
rrdtool graph /tmp/nest_b.png --height '150' "${flags[@]}" -P "${def[@]}" > /dev/null

def=(
  "DEF:state=${rrd}:state:AVERAGE"
  'AREA:state#0000FF:HVAC\n'
  "DEF:fan=${rrd}:fan:AVERAGE"
  'LINE:fan#FF0000:Fan\n'
)
rrdtool graph /tmp/nest_c.png --height '150' "${flags[@]}" -P "${def[@]}" > /dev/null

convert -append /tmp/nest_[abc].png "${out_dir}/nest.png"
rm /tmp/nest_[ab].png

